## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [10]:
boston=datasets.load_boston()
xTrain, xTest, yTrain, yTest = train_test_split(boston.data, boston.target, test_size=0.2, random_state=2)

In [25]:
linearModel=linear_model.LinearRegression()
linearModel.fit(xTrain, yTrain)
yPred=linearModel.predict(xTest)
yPred

array([23.01506153, 21.2115869 , 33.71590384, 31.56542369,  3.1826268 ,
        3.15381954, 27.40305304, 22.2126176 , 14.86506114, 21.34105453,
       30.95942941, 26.70065029, 21.12624382, 18.37282564, 17.64315354,
       25.38194186, 24.42970445, 13.36957057,  8.66686786, 18.57490534,
       21.73966467, 20.34270529, 36.5461105 , 20.59627495, 19.87979627,
       15.75766967, 37.11632999, 34.85897895, 30.83458635, 23.23441285,
       18.68278505, 20.749546  , 31.84560076, 30.20214207, 13.3861702 ,
       15.87078398, 13.70766096, 23.74163998, 25.95135088, 23.18325878,
       28.99906539, 12.50341936, 31.08347911,  6.39401895, 23.71801218,
       20.61523929, 33.15362417, 19.21862493, 35.89603081,  0.82365329,
       31.90288611, 31.69640543,  6.58849712, 34.62762996, 20.41162545,
       19.69277608, 19.53445865, 18.58689088, 15.81420496, 22.98764309,
       19.65947045, 16.36377019, 18.48783369, 32.76568172, 35.49022568,
       24.58349631, 41.5854766 , 32.94818456, 14.60990256, 27.43

In [26]:
mean_squared_error(yTest, yPred)

18.49542012244866

In [31]:
lassoModel=linear_model.Lasso(alpha=0.0005)
lassoModel.fit(xTrain, yTrain)
yPred=lassoModel.predict(xTest)
yPred

array([23.028189  , 21.237483  , 33.71616264, 31.56135005,  3.18172738,
        3.14871091, 27.39541613, 22.22550181, 14.85209159, 21.37455146,
       30.9617674 , 26.69645437, 21.12410175, 18.37578917, 17.64050331,
       25.37800931, 24.40867541, 13.37966272,  8.66042466, 18.58805606,
       21.75794076, 20.34025627, 36.55451069, 20.60721295, 19.88778504,
       15.76873318, 37.11165907, 34.85019304, 30.84320548, 23.23556074,
       18.67504108, 20.76661994, 31.84314363, 30.19831063, 13.38978863,
       15.90048562, 13.70939209, 23.75329111, 25.9513339 , 23.16980054,
       28.99000403, 12.50471561, 31.08359585,  6.39449096, 23.70532761,
       20.62036972, 33.15163345, 19.23062116, 35.90405433,  0.80054731,
       31.899149  , 31.70372222,  6.58796847, 34.62327464, 20.40928786,
       19.6994907 , 19.54654985, 18.59113986, 15.81951893, 22.9732884 ,
       19.64498845, 16.38438471, 18.49007688, 32.76251457, 35.48335239,
       24.58366822, 41.57938227, 32.93362836, 14.61306699, 27.42

In [32]:
mean_squared_error(yTest, yPred)

18.500391573503432

In [33]:
ridgeModel=linear_model.Ridge(alpha=1.0)
ridgeModel.fit(xTrain, yTrain)
yPred=ridgeModel.predict(xTest)
yPred

array([23.56740761, 22.51371986, 33.73094724, 31.3611396 ,  3.12619096,
        2.9247266 , 27.06004131, 22.77296824, 14.21703804, 22.78573067,
       31.07772674, 26.50343753, 21.01077162, 18.48362358, 17.54936672,
       25.17035299, 23.73589565, 13.81038374,  8.40781384, 19.14092359,
       22.51820415, 20.22943927, 36.9293129 , 21.06712221, 20.21692712,
       16.23561443, 36.86445809, 34.47481217, 31.20553973, 23.2621229 ,
       18.304427  , 21.47880204, 31.74443782, 30.01980363, 13.51160342,
       17.14124878, 13.77605563, 24.46419808, 25.9535445 , 22.56873405,
       28.59323144, 12.54262737, 31.09946848,  6.38948552, 23.12946598,
       20.82703962, 33.0713204 , 19.73549985, 36.24216689, -0.20390136,
       31.74117215, 32.05121813,  6.56025013, 34.42801638, 20.26400095,
       19.96614616, 20.03487124, 18.76765096, 16.02232156, 22.56486475,
       18.96266705, 17.22770361, 18.56457359, 32.63066147, 35.19002127,
       24.59338984, 41.33819858, 32.52864187, 14.72847913, 27.14

In [28]:
mean_squared_error(yTest, yPred)

18.956427878959033

In [30]:
ridgeModel.coef_

array([-1.06294853e-01,  4.00711492e-02, -4.38821776e-02,  2.99082843e+00,
       -9.14911491e+00,  3.66794458e+00,  3.35677782e-03, -1.27743163e+00,
        3.07729982e-01, -1.22746288e-02, -9.51266951e-01,  1.20968072e-02,
       -5.71006393e-01])