## [作業重點]
使用 Sklearn 中的線性迴歸模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義

## 作業
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [30]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [4]:
wine=datasets.load_wine()
X=wine['data']
Y=wine['target']

In [16]:
trainX, testX, trainY, testY = train_test_split(X, Y, test_size=0.3, random_state=5)

In [12]:
trainY

array([2, 1, 2, 1, 0, 1, 1, 0, 2, 0, 1, 2, 2, 0, 0, 1, 2, 1, 1, 2, 2, 2,
       1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 0, 2, 1, 0, 2, 2, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 2, 2, 0, 2, 0,
       2, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0,
       1, 0, 0, 2, 1, 1, 2, 0, 0, 0, 2, 1, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1,
       0, 0, 1, 1, 2, 0, 2, 1, 2, 0, 1, 2, 1, 1])

In [55]:
LogisticModel=linear_model.LogisticRegression()
LogisticModel.fit(trainX, trainY)
Y_pred=LogisticModel.predict(testX)
Y_pred

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


array([0, 1, 0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 1, 2, 2, 0,
       2, 1, 0, 2, 0, 1, 0, 1, 1, 0])

In [27]:
accuracy_score(testY, Y_pred)

0.9259259259259259

In [50]:
boston=datasets.load_boston()
X=boston['data']
Y=boston['target']

In [63]:
trainX, testX, trainY, testY = train_test_split(X, Y, test_size=0.3, random_state=5)
linearModel=linear_model.LinearRegression()
linearModel.fit(trainX, trainY)
Y_pred=linearModel.predict(testX)
Y_pred

array([37.38997666, 31.56794193, 27.13373886,  6.55117625, 33.69310848,
        5.54919368, 27.10005629, 29.82980986, 26.44622421, 22.38873525,
       32.24739998, 21.74892356, 23.42369575, 33.57974607, 28.31450393,
       15.36502049,  0.17012738, 18.7085528 , 14.6046344 , 10.80263809,
        3.18552876, 19.39248482, 38.33235502, 24.40456217, 31.99950162,
       11.35200963, 24.922899  , 23.39214933, 22.75072363, 21.09584945,
       16.12295584,  7.53544865, 17.59797845, 22.82206974, 29.26790527,
       18.8053497 , 28.33669828,  8.60467923, 41.63227506, 34.1975156 ,
       20.11767808,  4.30987094, 29.61105614, 11.92148423, 27.22215387,
       30.94537934, -6.26468581, 19.96366597, 21.59383857, 13.6435966 ,
       20.49852424, 19.9376828 , 23.65383649, 13.51654696, 17.64433366,
       25.20135154, 35.31489968, 15.25337249, 28.51004736, 21.85251949,
       20.66385004, 26.03157156, 14.71628387, 32.34648274, 20.7126339 ,
       12.16905109, 19.60990611, 25.19479418, 21.78988729, 21.17

In [67]:
mean_squared_error(testY, Y_pred)

30.697037704088483

In [68]:
r2_score(testY, Y_pred)

0.6771696999851703